Create FFI for cgo
dusk-network/bls12_381-sign pull request #6
Opened 2020-10-25 11:28 UTC by julesdesmit

Fixes #5

2020-10-25 12:07 UTC, ZER0 commented on src/lib.rs
> +#[cfg(feature = "cgo")]
You don't need that.
To be clear, the `bls12_381-sign` can be seen in two ways:

1. It's a rust library that can be used by regular rust code
2. It's a rust library that will be used only (currently) for cgo purpose

If it's the first, then `bls12_381-sign` shouldn't be aware of cgo at all. In that case you should have a `bls12_381-sign-ffi` (or whatever you want to call it) crate that use `bls12_381-sign` as library and exports the methods to C.

If it's the second, then the solely purpose of this library is to be used by cgo, so there is no reason why it should be generic. It means, where you still have your public function etc, you use directly the `extern "C"` for the actual FFI, since there is no other purpose than be used in C / CGO, therefore it can be only compiled in such way.

Hope it's clear

2020-10-25 12:16 UTC, julesdesmit commented on src/lib.rs
> +#[cfg(feature = "cgo")]
I see. It is intended to be used by the rust node directly later on, so I think it will make sense to have a separate `ffi` crate. I will change this PR and issue to concern adding the needed conversion functions and the `#[repr(transparent)]` flags.

2020-10-25 12:44 UTC, ZER0 commented on src/lib.rs
> +#[cfg(feature = "cgo")]
Keep in mind, even if it's going to be used later on ONLY by rust there is no need for a separate crate.

The key point if there is now the need to have code that are using this crate both from C (or cgo) and Rust.

And I don't think so. We're using this crate now only for C, and then we'll switch to Rust. So I will basically keep the code as is, using only one crate, adding the module for the ffi here, that basically we'll be removed later and that's it. I wouldn't use any feature flag for that.

2020-10-25 12:45 UTC, julesdesmit commented on src/lib.rs
> +#[cfg(feature = "cgo")]
Ah, I see. That does make more sense.

2020-10-27 13:25 UTC, julesdesmit commented
Rustfmt check is currently failing, due to the fact that it is not available for the current nightly. You can manually check with just running the CI command locally.

2020-10-28 14:49 UTC, ZER0 requested changes
As mentioned let's finish this version where we code / decode every time the argument passed, and once we have it properly done I will suggest to spend a bit of time investigating about the other version we discussed, where you let Rust allocate the object once and Go using the pointer to such structure, and benchmark it to see if there is a gain that is significant for us (we should just test a couple of method, the slower ones, not port all of the lib yet)

2020-10-28 14:49 UTC, ZER0 commented on src/ffi.rs
> +const BLS_VERIFICATION_FAILED: c_int = 2;
You can keep the `BLS_OK` if you want, but I would remove the other two. Basically those are the errors (that you already have in `Error` module), so I would implement something like a `impl From<Error> for c_int`.
Ideally you could also avoid that, changing slightly the implementation of the errors enum in Rust, but I want to keep the ffi and the actual library as much as separate as possible.

2020-10-28 14:49 UTC, ZER0 commented on src/ffi.rs
> +}
This should be something more like this:
```rust
pub unsafe extern "C" fn generate_keys(sk_ptr: *mut u8, pk_ptr: *mut u8) {
    let sk = SecretKey::new(&mut rand::thread_rng());
    let pk = PublicKey::from(&sk);

    ptr::copy_nonoverlapping(&sk.to_bytes()[0] as *const u8, sk_ptr, SK_SIZE);
    ptr::copy_nonoverlapping(&pk.to_bytes()[0] as *const u8, pk_ptr, PK_SIZE);
}
```

(the `ptr` is from the `std::ptr`)

You might want to use some pointers arithmetic as well in the code below, instead of using `from_raw_parts_mut` / `copy_from_slice` pair.

2020-10-28 14:49 UTC, ZER0 commented on src/ffi.rs
> +    };
Assuming you have the errors impl mentioned, this will be:
```rust
let sk = match SecretKey::from_bytes(&*sk_ptr) {
    Ok(sk) => sk,
    Err(err) => return err.into()
}
```

Now, you can see that is more elegant because it doesn't require to decide which error propagate, it assume it will be converted by whatever error is returned from `from_bytes`.

Therefore, since you're using this patter a lot, you might want to create a local small macro that do this job for you, something like:

```rust
macro_rules! unwrap_or_bail {
    ( $e:expr ) => {
        match $e {
            Ok(v) => v,
            Err(e) => return e.into(),
        }
    }
}
```

And therefore you will have:
```rust
let sk = unwrap_or_bail!(SecretKey::from_bytes(&*sk_ptr));
```

2020-10-28 14:49 UTC, ZER0 commented on src/ffi.rs
> +    match apk.verify(&sig, &msg).is_ok() {
I don't recall but why `verify` doesn't return a boolean? It looks to me that it should just return `true` or `false`, unless it's possible that returns multiple errors other than `BLS_VERIFICATION_FAILED`.

2020-10-28 14:49 UTC, ZER0 commented on src/ffi.rs
> +    sig_slice.copy_from_slice(&sig.to_bytes());
As mentioned, you might want to copy directly from pointers, check the code for generate the keys – and apply to the whole FFI when it makes sense.

2020-10-28 14:49 UTC, ZER0 commented on src/ffi.rs
> +            PublicKey::from_bytes(&arr).expect("Invalid public key bytes")
Here you're panicking but instead you should not do that but instead return the error and so you can return `Error::InvalidBytes` (and properly casting to `c_int` as shown before).

2020-10-28 14:49 UTC, ZER0 commented on src/ffi.rs
> +            Signature::from_bytes(&arr).expect("Invalid signature bytes")
Same here, you should return the error and properly casting to `c_int` instead of panicking.

2020-10-28 14:49 UTC, ZER0 commented on src/keys/apk.rs
> +    pub fn to_bytes(&self) -> [u8; 96] {
You should implement a `const fn` called `serialized_size` and use that. Something like:

```rust
impl APK {
     pub const fn serialized_size() -> usize {
         96
     }
…
```

Then since is a constant function, you can use it as:
```rust
pub fn to_bytes(&self) -> [u8; APK::serialized_size()] {
```

2020-10-28 14:49 UTC, ZER0 commented on src/ffi.rs
> +const PK_SIZE: usize = 96;
If those are the size for the serialized representation you might want to implement `serialized_size` associated function. Something like:
```rust
const SK_SIZE: usize = SecretKey::serialized_size();
const PK_SIZE: usize = PublicKey::serialized_size();
const SIG_SIZE: usize = Signature::serialized_size();
```

See my comment about `to_bytes` / `from_bytes`.

2020-10-28 14:49 UTC, ZER0 commented on src/keys/apk.rs
> +    pub fn from_bytes(bytes: &[u8; 96]) -> Result<Self, Error> {
Same here, clearly.

2020-10-29 08:48 UTC, julesdesmit commented on src/ffi.rs
> +    match apk.verify(&sig, &msg).is_ok() {
It can also return `BLS_INVALID_BYTES`.

2020-10-29 12:21 UTC, ZER0 approved these changes
LGTM, with the `from_bytes` simplification before the merge.

2020-10-31 13:00 UTC, merged