Set crate-type to rlib, implement Canon for all needed types
dusk-network/bls12_381-sign pull request #9
Opened 2021-01-04 18:59 UTC by julesdesmit

Fixes #8

2021-01-06 14:46 UTC, CPerezz approved these changes
LGTM. Just the release stuff.

2021-01-06 14:46 UTC, CPerezz commented on Cargo.toml
> +dusk-bls12_381 = { git = "https://github.com/dusk-network/bls12_381", branch = "canon-groups", default-features = false }
We should release a tag first for thid crate.

2021-01-06 14:49 UTC, julesdesmit commented on Cargo.toml
> +dusk-bls12_381 = { git = "https://github.com/dusk-network/bls12_381", branch = "canon-groups", default-features = false }
Yep, that was a given. I am waiting on the last PR to merge on the BLS repo, then I can fix this line.

2021-02-05 15:32 UTC, CPerezz commented
CI failing @julesdesmit . Maybe wrong jubjub version according to the errors?

2021-02-05 15:46 UTC, vlopes11 requested changes
Few nits

2021-02-05 15:46 UTC, vlopes11 commented on Cargo.toml
> +dusk-bls12_381 = { git = "https://github.com/dusk-network/bls12_381", tag = "v0.6.0" }
Replace for `dusk-bls12_381 = "0.6"`

2021-02-05 15:46 UTC, vlopes11 commented on src/ffi.rs
> +#![cfg(feature = "default")]
`default` feature should never be checked, Check the specific features instead (e.g. `std`)

2021-02-05 15:46 UTC, vlopes11 commented on src/keys/apk.rs
> +    #[cfg(feature = "std")]
I believe it is no longer a requirement to have `std` for the `bls` affine points definition. This is supposed to be fixed in the last versions

2021-02-05 15:46 UTC, vlopes11 commented on src/keys/apk.rs
> +    #[cfg(feature = "std")]
Same as above; Likely `std` is not required

2021-02-05 15:46 UTC, vlopes11 commented on src/keys/public.rs
> +    #[cfg(feature = "std")]
Same as above

2021-02-05 15:46 UTC, vlopes11 commented on src/keys/public.rs
> +    #[cfg(feature = "std")]
Same as above

2021-02-05 15:47 UTC, vlopes11 commented on Cargo.toml
> +dusk-bls12_381 = { git = "https://github.com/dusk-network/bls12_381", tag = "v0.6.0" }
Check also if `default-features = false` applies because otherwise the crate will be imported as `std`

2021-02-05 15:56 UTC, vlopes11 approved these changes
LGTM, one nit

2021-02-05 15:56 UTC, vlopes11 commented on Cargo.toml
> +dusk-bls12_381 = "0.6"
One last thing. Should have `default-features = false` because other way it implies the `std` import when we require `dusk-bls12_381/default` only if `std` is set for this crate

2021-02-05 15:59 UTC, julesdesmit commented on Cargo.toml
> +dusk-bls12_381 = "0.6"
In that case, I do need to guard the verification functions with feature flags for `std`.

2021-02-05 16:01 UTC, merged